# Generated by Django 4.1.7 on 2023-04-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_cartitem_is_wishlist_item_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_wishlist_item',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
