# Generated by Django 4.1.7 on 2023-04-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
